### ISSUE TITLE
Proxy Setting

### ISSUE THREAD

**Issue by HenryQW** [mrgodhani/raven-reader#121]
Hi, thanks for the great work.

I noticed that Raven doesn't work behind a proxy and there isn't a place to set it.

Possible npm package to support that: https://www.npmjs.com/package/http-proxy

**Comment by mrgodhani** [comment]
@HenryQW Proxy you mean for images/fetching feeds?

**Comment by HenryQW** [comment]
Hi @mrgodhani , I was referring to a corporate proxy.

**Comment by mrgodhani** [comment]
> Hi @mrgodhani , I was referring to a corporate proxy.

Ye I am not sure about corprorate proxy.  But at moment app isn't using any proxy. If you can specify in more detail where that proxy would be used ? or for what reasons that might be helpful.

**Comment by HenryQW** [comment]
Basically all traffic must go through the corporate proxy, if the proxy isn't set, Raven will not be able to connect to the outside world at all, thus always returning `No feed found`.

For example Docker has this proxy settings section (which respects system proxy environment HTTP_PROXY or HTTPS_PROXY)

![image](https://user-images.githubusercontent.com/5896343/47036391-5490fe00-d174-11e8-8446-7f0f9b2ff899.png)

**Comment by mrgodhani** [comment]
@HenryQW I see. Ok I will look into it.

**Comment by mrgodhani** [comment]
In electron there is setting Proxy option.

```
mainWindow = new BrowserWindow({
    "width": 970,
    "height": 500,
    "center": true,
    'title': 'Main window',
});
mainWindow.webContents.session.setProxy({proxyRules:"socks5://114.215.193.156:1080"}, function () {
    mainWindow.loadURL('https://whatismyipaddress.com/');
});
```

One of the example. But question is it bypassing local proxies ? Or you want option to configure your own?

**Comment by HenryQW** [comment]
> In electron there is setting Proxy option.
> 
> ```
> mainWindow = new BrowserWindow({
>     "width": 970,
>     "height": 500,
>     "center": true,
>     'title': 'Main window',
> });
> mainWindow.webContents.session.setProxy({proxyRules:"socks5://114.215.193.156:1080"}, function () {
>     mainWindow.loadURL('https://whatismyipaddress.com/');
> });
> ```
> One of the example. But question is it bypassing local proxies ? Or you want option to configure your own?

Yeah there needs to be an option to configure, as corporate proxy is for internal use only.

**Comment by mrgodhani** [comment]
@HenryQW https://github.com/mrgodhani/raven-reader/releases/tag/v0.3.6 I added proxy configuration settings. I have no proper way to test this. So might need your help and see if it is working.

**Comment by mrgodhani** [comment]
Did some improvements https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.1. Should work now. Please create a separate issue if the problem exists.
