### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by logix2** [mrgodhani/raven-reader#129]
I see that Linux support is mentioned in the roadmap, so I thought I'd create an issue for this so I (and anyone else interested) can be notified when this is "fixed".

**Comment by mrgodhani** [comment]
@logix2 Working on this. But problem at moment I am facing is building for linux via electron-builder. Seems not working / or has some known issues.

**Comment by wetterSpitze** [comment]
> I see that Linux support is mentioned in the roadmap, so I thought I'd create an issue for this so I (and anyone else interested) can be notified when this is "fixed".

would be awesome if the reader works on linux!! :+1: 
I've been searching for such a tool for a very long time and according to the screenshots published
raven is exactly what i was looking for.

Props @mrgodhani for this awesome project!!

**Comment by mrgodhani** [comment]
@wetterSpitze Thanks for the kind words. I will try to build for Linux right now it's simply blocked as somehow I am not able to build one

**Comment by mrgodhani** [comment]
@logix2 @wetterSpitze App for Linux is here https://github.com/mrgodhani/raven-reader/releases/tag/v0.3.7 Download Snap or AppImage file

**Comment by wetterSpitze** [comment]
> @logix2 @wetterSpitze App for Linux is here https://github.com/mrgodhani/raven-reader/releases/tag/v0.3.7 Download Snap or AppImage file

Very nice to see the project progressing :+1: . And thanks for this very quick effort to port your app on Linux!!
