### ISSUE TITLE
Raven icon not showing in Ubuntu Dock

### ISSUE THREAD

**Issue by IjonFryderyk** [mrgodhani/raven-reader#207]
Raven (AppImage) icon is not showing in Ubuntu Dock (Ubuntu 18.04). Adding StartupWMClass to Raven .desktop file doesn't solve the problem. 

https://github.com/AppImage/pkg2appimage/issues/199
https://askubuntu.com/questions/971388/few-application-icons-not-appearing-in-ubuntu-dock-after-upgrading-to-ubuntu-17

PS 
Is there any way to disable Raven indicator?

**Comment by mrgodhani** [comment]
I see the icon now. You can now install using snap https://snapcraft.io/raven-reader. Closing this for now if it re-occurs will try to fix.
