### ISSUE TITLE
inoreader integration needed

### ISSUE THREAD

**Issue by kid1412621** [mrgodhani/raven-reader#210]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
use inoreader for sync

**Describe alternatives you've considered**
 

**Additional context**

**Comment by mrgodhani** [comment]
@kid1412621 That's coming up in next release

**Comment by kid1412621** [comment]
Can't wait.

**Comment by mrgodhani** [comment]
@kid1412621  integrated https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.1 closing it.

**Comment by kid1412621** [comment]
> @kid1412621 integrated https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.1 closing it.

Thanks for your work. But I think it's not available to sync read progress.

**Comment by mrgodhani** [comment]
@kid1412621 Right now it syncs feed and not articles. And articles would be grabbed latest not the previous. If that's what you meant by reading progress.

**Comment by kid1412621** [comment]
I mean syncing the articles of feeds what I’ve read or not.
