### ISSUE TITLE
Would pls add Fever Api Support?

### ISSUE THREAD

**Issue by matoung** [mrgodhani/raven-reader#222]
**Is your feature request related to a problem? Please describe.**
- No issue

**Describe the solution you'd like**
- Fever API is common support by many self-host RSS server like TT-RSS, miniflux. On MacOS/iOS,  reeder app can sync with it, but on windows, I couldn't find one replacement, it is very helpful if raven reader support this feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by matoung** [comment]
Recently I did it by myself, realize fever api sync and so on base on raven reader, cause a lot of custom changes, named it Spark Reader([https://github.com/matoung/SparkReader](https://github.com/matoung/SparkReader))
Thanks for raven reader and the authors, this issue can be closed.

**Comment by mrgodhani** [comment]
@matoung Nice work there. Do you mind if I use some of your solution that solves the current problem I am working on? Also, you could have contributed to this repo.

**Comment by matoung** [comment]
@mrgodhani You can use anything, with pleasure :)
