### ISSUE TITLE
navigation - navigate between stories with j/k or arrow up and arrow down

### ISSUE THREAD

**Issue by thisisshi** [mrgodhani/raven-reader#249]
**Is your feature request related to a problem? Please describe.**
Browsing stories with j/k or arrow up and arrow down would make it easier to quickly get through a feed

**Describe the solution you'd like**
When in the main view pressing j will advance to the next story and pressing k will go to to the previous story.

**Describe alternatives you've considered**
tab + enter works to advance to the next story but requires two key strokes, same with tab + shift + enter

**Additional context**
Gmail has support for this type of navigation in its settings for example

**Comment by mrgodhani** [comment]
https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.2 Released in v0.4.2
