### ISSUE TITLE
ssl expiration on website

### ISSUE THREAD

**Issue by thisisshi** [mrgodhani/raven-reader#250]
**Describe the bug**
The SSL Certificate on the website is expired:

```
ravenreader.app uses an invalid security certificate.

The certificate expired on January 13, 2019, 7:38:02 PM GMT-5. The current time is February 1, 2019, 12:02 AM.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

**To Reproduce**
Open a browser and introspect the cert

**Expected behavior**
The certificate is not expired

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox 64.0.2

**Additional context**
N/A

**Comment by mrgodhani** [comment]
@thisisshi fixed thank you for reporting
