### ISSUE TITLE
Please support cyrilic fonts

### ISSUE THREAD

**Issue by ZRabadaber** [mrgodhani/raven-reader#269]
Help pls.
For example use this links:
https://www.finam.ru/analysis/conews/rsspoint
http://bonds.finam.ru/news/today/rss.asp
version 0.4.1

![example](https://user-images.githubusercontent.com/28845947/52487529-e793ef00-2bce-11e9-936b-a683d1858c97.jpg)

**Comment by mrgodhani** [comment]
@ZRabadaber That helps. I will test and fix

**Comment by mrgodhani** [comment]
@ZRabadaber It's bug from Mercury Parser side that I am using in the app. It's reported there https://github.com/postlight/mercury-parser/issues/263

**Comment by mrgodhani** [comment]
Fixed in https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.3
