### ISSUE TITLE
Raven Crash for Atom 1.0 feed

### ISSUE THREAD

**Issue by cricrazy** [mrgodhani/raven-reader#289]
**Describe the bug**
I am trying to add RSS feed using "Kill the Newsletter" service. I have the XML file which is validated. But Raven Reader crashes and it fails to add. 

**To Reproduce**
1. Open 'Raven Reader'.
2. Click on 'Add'.
3. Enter `https://www.kill-the-newsletter.com/feeds/d6s8iyxebya5iygcybbu.xml` and press Enter.
4. See error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
[The feed is validated here. ](https://validator.w3.org/feed/check.cgi?url=https://www.kill-the-newsletter.com/feeds/d6s8iyxebya5iygcybbu.xml
)

**Comment by mrgodhani** [comment]
Fixed in https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.3
