### ISSUE TITLE
Checksum Mismatch - SHA512 on Linux.yml

### ISSUE THREAD

**Issue by ADun3306x** [mrgodhani/raven-reader#298]
Hi

I ran a standard check on the SHA512 listed on linux.yml against the latest linux x86_64_AppImage.

Returns a checksum validation mismatch.. confirmed on 2 different validation apps.

I checked the other SHA & MD5 codes to see if this has been a typo in the YML, however none also match.  Can you please check the file validity in case of issues with the package?  

Rgds

Al

**Comment by mrgodhani** [comment]
@ADun3306x you mean latest-linux.yml?

**Comment by ADun3306x** [comment]
Hi...@mrgodhani  

Yes, I found that the SHA512 string in the latest-linux.yml doesnt authenticate when running an SHA512 checksum validation on the x86_64 Linux Appimage. 

Something is either definitely up with this file, or an error has been made with the original checksum in the latest-linux.yml file

Here are the steps followed for your reference.. I performed 2 tests using different controls, but both resulted in the same information.

Rgds

Al

---------------------------------------------
**1.** Downloaded the latest x86_64 version for Linux (for Build 0.4.1)
**2.** Downloaded the latest-linux.yml file
**3.** Reviewed the YML:

**SHA512 listed as** tV6omX2ifC7jrz4ytvLGSiasHNd540gwa2QPCJa/eVMeEiRXvIa3sqhkYBST5uJH68oCJi/y3/3YbZDcDIDhXw==

**4.** Accessed the x86_64 file properties using Ubuntu's Digest Tab and checked against SHA512

**Results:**
**SHA512 =** b55ea8997da27c2ee3af3e32b6f2c64a26ac1cd779e348306b640f0896bf79531e122457bc86b7b2a864601493e6e247ebca02262ff2dffdd86d90dc0c80e15f

Results in checksum validation mismatch 

**5.** Cross validated results using app Checksum Validator (_https://github.com/alexanderwe/checksum-validator_)

**a.** Dragged x86_64 file into the validator target area
**b.** Entered the Checksum contained within the YML
**b.** Selected SHA512 from the list & Executed

**Result =** Error Checksum Mismatch
{"checksum":"b55ea8997da27c2ee3af3e32b6f2c64a26ac1cd779e348306b640f0896bf79531e122457bc86b7b2a864601493e6e247ebca02262ff2dffdd86d90dc0c80e15f","algorithm":"SHA512"}],
"checkString":"tV6omX2ifC7jrz4ytvLGSiasHNd540gwa2QPCJa/eVMeEiRXvIa3sqhkYBST5uJH68oCJi/y3/3YbZDcDIDhXw==",
"checkAlgorithm":"SHA512","didMatch":false,

--------------------------------------------------------------

**Comment by mrgodhani** [comment]
https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.5 This should be fine now
