### ISSUE TITLE
Can't subscribe to RSS feed

### ISSUE THREAD

**Issue by darakian** [mrgodhani/raven-reader#367]
**Describe the bug**
Just downloaded the macos dmg and tried to subscribe to 
`https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss-analyzed.xml`

UI indicates success, but nothing happens.

**Comment by mrgodhani** [comment]
Seems like RDF isn't supported with parser we use. Reported it https://github.com/bobby-brennan/rss-parser/issues/107

**Comment by darakian** [comment]
Cool. Thanks for passing it along.

**Comment by mrgodhani** [comment]
https://github.com/mrgodhani/raven-reader/releases/tag/v0.5.0 Added support for RDF

**Comment by darakian** [comment]
Sorry to say, but while it parses the feed now the content isn't very meaningful.
![image](https://user-images.githubusercontent.com/3607524/56459981-7439f680-6350-11e9-9eb6-4732e8a0b216.png)

**Comment by mrgodhani** [comment]
<img width="1316" alt="Screen Shot 2019-04-20 at 12 44 54 PM" src="https://user-images.githubusercontent.com/1529009/56460019-2336fc00-636a-11e9-846d-5a80e53b221a.png">
It should show description. Unfortunately, the parser won't work with all contents. If we find it is not able to parse it. We will replace it with a description excerpt.
