### ISSUE TITLE
Light mode text color issue

### ISSUE THREAD

**Issue by BenjaminHoegh** [mrgodhani/raven-reader#373]
articles text keep being white in Light mode but should turn dark

**Comment by balag12** [comment]
I am also encountering this issue. Latest snap version, on Manjaro Cinnamon.

**Comment by mrgodhani** [comment]
Ah, I see that now. Will work on the fix ASAP. Sorry for late replies guys getting busier at work nowadays.

**Comment by mrgodhani** [comment]
Fixed https://github.com/mrgodhani/raven-reader/releases/tag/v0.5.1
