### ISSUE TITLE
No text in articles (only images)

### ISSUE THREAD

**Issue by larsen0815** [mrgodhani/raven-reader#403]
**Describe the bug**
I only see some images in blog posts, but no text. Pretty much the oppsite of #286.

**To Reproduce**
Not sure
- Installed Raven Reader on Windows 10, 1903
- Imported 5 feeds via OPML vom RssOwlnix

**Comment by larsen0815** [comment]
![Clipboard-1](https://user-images.githubusercontent.com/2345512/58421002-24f18f00-808f-11e9-8a8d-7338f83d05d9.png)

**Comment by mrgodhani** [comment]
@larsen0815 Did you downloaded latest version? https://github.com/mrgodhani/raven-reader/releases/tag/v0.5.1 that was fixed there

**Comment by larsen0815** [comment]
I thought I did, because I downloaded it from https://ravenreader.app/, but apparently it's not hosting the latest version (only 0.5.0). Fixed in 0.5.1, thanks!

**Comment by mrgodhani** [comment]
@larsen0815 Sorry about that. The website needs some update on the landing page so working on it.
