### ISSUE TITLE
Please support cyrilic fonts

### ISSUE THREAD

**Issue by uitlaber** [mrgodhani/raven-reader#80]
![image](https://user-images.githubusercontent.com/18505561/45264110-1445ae00-b459-11e8-937a-c0d3ece22737.png)

**Comment by ZloyRabadaber** [comment]
I also have this problem

**Comment by mrgodhani** [comment]
@adrianratajczak @ZloyRabadaber Integrated https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.1. Let me know if that helps. If not please create new issue.

**Comment by ZRabadaber** [comment]
> @adrianratajczak @ZloyRabadaber Integrated https://github.com/mrgodhani/raven-reader/releases/tag/v0.4.1. Let me know if that helps. If not please create new issue.

Not work. I use rss https://www.finam.ru/analysis/conews/rsspoint
![example](https://user-images.githubusercontent.com/28845947/52486769-1741f780-2bcd-11e9-9451-6bc48a603512.jpg)

**Comment by ZRabadaber** [comment]
may be you font do not have cyrilic charset?
